### ISSUE TITLE
Promise.resolve is not a function

### ISSUE THREAD

**Issue by saumilsdk** [acrisci/simple-breakpad-server#14]
Got an error while clicking on "view" to open symbol file on "http://localhost:1127/symfiles"

Unhandled rejection TypeError: Promise.reslove is not a function
    at Model.Symfile.getContents (/home/skapadia/projects/simple-breakpad-server/src/model/symfile.coffee:83:13)
    at Model.<anonymous> (/home/skapadia/projects/simple-breakpad-server/src/app.coffee:289:17)
    at Model.tryCatcher (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/skapadia/projects/simple-breakpad-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by Jimbly** [comment]
Thanks for the report, I'll look into it, probably related to my recent change. CoffeeScript and Promises are not my forte =).

**Comment by Jimbly** [comment]
Actual error was "Promise.reslove is not a function", just a simple typo, has been fixed.  If you're using the latest version from Git (looks like you are), and plan on using this in production, I highly recommend setting `filesInDatabase: false` in the config, or using a database other than sqllite (which keeps everything in memory).
