### ISSUE TITLE
Not able to open crashdump

### ISSUE THREAD

**Issue by saumilsdk** [acrisci/simple-breakpad-server#17]
**Browser Error:**
Bad things happened:
2018-03-27 12:00:14: minidump.cc:4693: ERROR: ReadBytes: read 4/32 2018-03-27 12:00:14: minidump.cc:4356: ERROR: Minidump cannot read header 2018-03-27 12:00:14: minidump_stackwalk.cc:87: ERROR: Minidump /tmp/tmp-3391B1NjaW540KhU.tmp could not be read

**Backend Error:**
Trace: Error: 2018-03-27 12:00:14: minidump.cc:4693: ERROR: ReadBytes: read 4/32
2018-03-27 12:00:14: minidump.cc:4356: ERROR: Minidump cannot read header
2018-03-27 12:00:14: minidump_stackwalk.cc:87: ERROR: Minidump /tmp/tmp-3391B1NjaW540KhU.tmp could not be read

    at ChildProcess.<anonymous> (/home/skapadia/projects/simple-breakpad-server/node_modules/minidump/lib/minidump.js:41:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

    at /home/skapadia/projects/simple-breakpad-server/src/app.coffee:136:13
    at Layer.handle_error (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:315:13)
    at /home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:275:10)
    at /home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/application.js:233:9
    at /home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:260:14)
    at Layer.handle_error (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:315:13)
    at /home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/index.js:275:10)
    at next (/home/skapadia/projects/simple-breakpad-server/node_modules/express/lib/router/route.js:127:14)
    at /home/skapadia/projects/simple-breakpad-server/src/app.coffee:300:16
    at /home/skapadia/projects/simple-breakpad-server/src/model/crashreport.coffee:61:7
    at ChildProcess.<anonymous> (/home/skapadia/projects/simple-breakpad-server/node_modules/minidump/lib/minidump.js:41:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by saumilsdk** [comment]
Forgot to specify parameter name "upload_file_minidump" while uploading file
