### ISSUE TITLE
Bad things happened:<br/> object null is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by WABWH** [acrisci/simple-breakpad-server#28]
When I upload a symbol file with curl, I encounter the following error：

**Bad things happened:<br/> object null is not iterable (cannot read property Symbol(Symbol.iterator))**

Some symbol files can be uploaded, and some symbol files will report this error。

**Comment by WABWH** [comment]
[object Object]
    at F:\mygitwork\simple-breakpad-server\src\app.coffee:137:13
    at Layer.handle_error (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\index.js:315:13)
    at F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\index.js:335:12)
    at next (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\index.js:275:10)
    at Immediate.<anonymous> (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\application.js:233:9)
    at Immediate._onImmediate (F:\mygitwork\simple-breakpad-server\node_modules\express\lib\router\index.js:635:15)
    at processImmediate (internal/timers.js:460:21)

**Comment by lykiao** [comment]
same issue here, can anyone help?

Running "watch" task
Waiting...
Listening on port 1127
[object Object]
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\src\app.coffee:137:13
    at Layer.handle_error (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:326:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\application.js:240:9
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:646:15
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:265:14)
    at Layer.handle_error (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:326:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle_error (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:326:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:97:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at methodOverride (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\method-override\index.js:79:5)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at urlencodedParser (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\body-parser\lib\types\urlencoded.js:100:7)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at jsonParser (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\body-parser\lib\types\json.js:119:7)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at decompress (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express-decompress\decompress.js:21:24)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at expressInit (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at query (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:175:3)
    at Function.handle (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\application.js:181:10)
    at mounted_app (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\application.js:237:10)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at expressInit (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at query (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:328:13)
    at D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\router\index.js:175:3)
    at Function.handle (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\application.js:181:10)
    at Server.app (D:\WorkSpace\MyTortoiseGit\simple-breakpad-server\node_modules\express\lib\express.js:39:9)
    at Server.emit (events.js:400:28)
    at parserOnIncoming (_http_server.js:900:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)

**Comment by ihangji** [comment]
Update  to "connect-busboy": "1.0.0"

**Comment by Jimbly** [comment]
I believe this is fixed with the latest version in Git (not published to NPM yet though, as I don't have access to that).  If nothing else, the actual error message will hopefully at least appear on the console now.
